### ISSUE TITLE
Game crashes at about 50 points

### ISSUE THREAD

**Issue by manolol1** [manolol1/EndlessRunner#1]
Exception in thread "main" java.lang.IllegalStateException: Array is empty.
        at com.badlogic.gdx.utils.Array.peek(Array.java:364)
        at xyz.manolol.endlessrunner.screens.GameScreen.render(GameScreen.java:123)
        at com.badlogic.gdx.Game.render(Game.java:48)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
        at xyz.manolol.endlessrunner.DesktopLauncher.main(DesktopLauncher.java:15)

**Comment by manolol1** [comment]
Might be caused by this:

        // Spawn new Obstacles
        if (obstacles.peek().x < viewport.getWorldWidth() - (obstacleDistance + MathUtils.random(-250.0f, +200.0f))) {
            spawnObstacle(viewport.getWorldWidth());
        }

because the array might be empty at that point. Probably need to implement a check before this.
